### PR TITLE
filter node with id

### PR DESCRIPTION
**Pull request by ghanbari**
node's text & id are flat and we can search node's id as regex too

### CODE REVIEW

**Comment by amsik** [comment]
Hi. Thanks for your contributing. But have you tried use regexp for id key now? I'm sure that it works.

```javascript
  const ccNodes = tree.findAll({id: /cc/})
```

**Comment by ghanbari** [comment]
@amsik it dose not work for me, it return all nodes.
`this.$refs.tree.findAll({id: /ROLE_MANAGE_USERS|ROLE_INSERT_USERS/})` return all nodes with any roles.
version: `0.2.47`

**Comment by amsik** [comment]
I've added you changes. You can one more way - use function.

```javascript
this.$refs.tree.findAll(function(node) {
 return /ROLE_MANAGE_USERS|ROLE_INSERT_USERS/.test(node.id)
})
```

I will add it to the docs.

**Comment by ghanbari** [comment]
@amsik thanks.

**Pull request merged**
