### PR TITLE
Original Item property & expandIconOnly option

### PR DESCRIPTION
**Pull request by OwenCalvin**
Now we can get the original object with the item property on event  
With expandIconOnly option, the a Node expand only when you click on the arrow

### CODE REVIEW

**Comment by OwenCalvin** [comment]
I also remove <a href="javascript:void(0)" ...> by a span because javascript:void(0 appear in the bottom left of the browser and that's ugly :)

**Comment by amsik** [comment]
* "Expand only on arrow" - https://amsik.github.io/liquor-tree/#Component-Options -> `parentSelect` option.
* link's href should be there because it has to call `focus` event (https://github.com/amsik/liquor-tree/blob/master/src/components/TreeNode.vue#L22). I don't remember, but it probably didn't work in IE without this attribute. Need check again

**Comment by OwenCalvin** [comment]
I didn't noticed the parentSelect property haha ...  I removed it

**Comment by OwenCalvin** [comment]
and I saw your replied to my issue for the selected item, the pull request is just for the javascript:void(0) now...

**Pull request closed without merging**
